// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

import (
	"github.com/Geawn/Ms_E-commerce_BE/order-service/internal/model"
)

type OrderEdge struct {
	Node *model.Order `json:"node"`
}

type Query struct {
}
