package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.70

import (
	"context"
	"fmt"

	models1 "github.com/Geawn/Ms_E-commerce_BE/content-service/internal/models"
)

// Page is the resolver for the page field.
func (r *queryResolver) Page(ctx context.Context, slug string) (*models1.Page, error) {
	panic(fmt.Errorf("not implemented: Page - page"))
}

// Menu is the resolver for the menu field.
func (r *queryResolver) Menu(ctx context.Context, slug string, channel string) (*models1.Menu, error) {
	panic(fmt.Errorf("not implemented: Menu - menu"))
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
